version: '2'
volumes: 
  db-data: 
    external: false

services:
  cache:
    image: memcached:1.4-alpine

  db:
    environment:
        POSTGRES_PASSWORD:
        POSTGRES_USER:
    image: postgres:9.5
    volumes: 
      - db-data:/usr/local/psql/data

  jobs:
    env_file: .env
    build: .
    volumes: 
      - .:/usr/src/app
    command: bundle exec rails jobs:work
    depends_on: 
      - db

  app:
    env_file: .env
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/usr/src/app
    ports: 
      - "3010:3000"
    depends_on: 
      - db